# Limpieza y merge de tablas de datos de enigh

In [86]:
# Importar librerias
import pandas as pd
import numpy as np

## Importacion de datos

In [87]:
# establecer columnas de datos
pob_cols = ['folioviv','foliohog','numren','sexo','edad','disc_ver','disc_oir','disc_brazo','disc_camin','disc_apren','disc_vest','disc_habla','disc_acti','nivelaprob']

ing_cols = ['folioviv','foliohog','numren','clave', 'ing_tri', 'entidad']

trab_cols = ['folioviv','foliohog', 'numren','id_trabajo','trapais', 'subor', 'indep', 'contrato', 'htrab', 'sinco', 'clas_emp', 'tipoact']

In [88]:
# establecer tipos de datos
tipo_pob = {
    'folioviv' : str,'foliohog' : str,'numren' : str ,'sexo' : str,'edad' : float,'disc_ver': str,'disc_oir' : str,'disc_brazo': str,'disc_camin':str,'disc_apren': str,'disc_vest':str,'disc_habla':str,'disc_acti':str,'nivelaprob':str
    }
tipo_ing = {
    'folioviv':str,'foliohog':str,'numren':str,'clave':str, 'ing_tri':float, 'entidad':str
}    
tipo_trab = {
    'folioviv':str,'foliohog':str, 'numren':str,'id_trabajo':str,'trapais':str, 'subor':str, 'indep':str, 'contrato':str, 'htrab':int, 'clas_emp': str, 'tipoact':str
}

In [89]:
# Importar datos
poblacion = pd.read_csv(r'/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Raw data/conjunto_de_datos_enigh2024_ns_csv/conjunto_de_datos_poblacion_enigh2024_ns/conjunto_de_datos/conjunto_de_datos_poblacion_enigh2024_ns.csv', usecols=pob_cols,dtype = tipo_pob)
ingreso = pd.read_csv(r'/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Raw data/conjunto_de_datos_enigh2024_ns_csv/conjunto_de_datos_ingresos_enigh2024_ns/conjunto_de_datos/conjunto_de_datos_ingresos_enigh2024_ns.csv', usecols = ing_cols, dtype = tipo_ing)
trabajos = pd.read_csv(r'/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Raw data/conjunto_de_datos_enigh2024_ns_csv/conjunto_de_datos_trabajos_enigh2024_ns/conjunto_de_datos/conjunto_de_datos_trabajos_enigh2024_ns.csv', usecols = trab_cols,dtype = tipo_trab)

In [90]:
# Exploracion de poblacion
print("*************** Poblacion ********************")
print("======= descripcion cuantis =======")
print(poblacion.describe())
print("======= Nulos ============")
print(poblacion.isnull().sum())

poblacion.head(10)

*************** Poblacion ********************
======= descripcion cuantis =======
                edad
count  308598.000000
mean       33.881305
std        21.779162
min         0.000000
25%        15.000000
50%        32.000000
75%        50.000000
max       106.000000
======= Nulos ============
folioviv          0
foliohog          0
numren            0
sexo              0
edad              0
disc_ver          0
disc_oir          0
disc_brazo        0
disc_camin        0
disc_apren        0
disc_vest         0
disc_habla        0
disc_acti         0
nivelaprob    10645
dtype: int64

,folioviv,foliohog,numren,sexo,edad,disc_ver,disc_oir,disc_brazo,disc_camin,disc_apren,disc_vest,disc_habla,disc_acti,nivelaprob
0,0100001901,1,01,1,32.0,1,1,1,1,1,1,1,1,03
1,0100001901,1,02,2,24.0,1,1,1,1,1,1,1,1,04
2,0100001901,1,03,2,5.0,1,1,1,1,1,1,1,1,01
3,0100001901,1,04,1,2.0,1,1,1,1,1,1,1,1,NaN
4,0100001902,1,01,1,48.0,1,1,1,1,1,1,1,1,07
5,0100001902,1,02,2,48.0,2,1,1,1,1,1,1,1,03
6,0100001902,1,03,1,22.0,1,1,1,1,1,1,1,1,07
7,0100001902,1,04,2,16.0,1,1,1,1,1,1,1,1,04
8,0100001904,1,01,2,60.0,1,1,2,1,2,1,1,1,03
9,0100001904,1,02,1,27.0,1,1,1,1,1,1,1,1,04

In [91]:
# Exploracion de trabajos
print("*************** trabajos ********************")
print("======= descripcion cuantis =======")
print(trabajos.describe())
print("======= Nulos ============")
print(trabajos.isnull().sum())

trabajos.head(10)

*************** trabajos ********************
======= descripcion cuantis =======
               htrab          sinco
count  164325.000000  164325.000000
mean       40.436550    6198.060691
std        18.702396    2650.938074
min         1.000000     980.000000
25%        28.000000    4111.000000
50%        43.000000    6121.000000
75%        48.000000    9111.000000
max       168.000000    9999.000000
======= Nulos ============
folioviv           0
foliohog           0
numren             0
id_trabajo         0
trapais            0
subor              0
indep         122407
contrato       50300
htrab              0
sinco              0
clas_emp       52114
tipoact       123157
dtype: int64

,folioviv,foliohog,numren,id_trabajo,trapais,subor,indep,contrato,htrab,sinco,clas_emp,tipoact
0,0100001901,1,01,1,1,1,NaN,1,48,8352,2,NaN
1,0100001901,1,02,1,1,1,NaN,2,45,5211,1,NaN
2,0100001902,1,01,1,1,1,NaN,1,48,9233,2,NaN
3,0100001902,1,03,1,1,1,NaN,1,48,9232,2,NaN
4,0100001904,1,01,1,1,1,NaN,2,12,4211,1,NaN
5,0100001904,1,01,2,1,1,NaN,2,18,4211,1,NaN
6,0100001904,1,02,1,1,1,NaN,2,40,2645,1,NaN
7,0100001905,1,01,1,1,1,NaN,1,48,8101,2,NaN
8,0100001905,1,02,1,1,1,NaN,2,10,9234,1,NaN
9,0100001905,1,03,1,1,1,NaN,2,32,9411,1,NaN

In [92]:
# Exploracion de ingreso
print("*************** ingreso ********************")
print("======= descripcion cuantis =======")
print(ingreso.describe())
print("======= Nulos ============")
print(ingreso.isnull().sum())

ingreso.head(10)

*************** ingreso ********************
======= descripcion cuantis =======
            ing_tri
count  3.915630e+05
mean   1.464697e+04
std    3.927904e+04
min    4.800000e-01
25%    1.760860e+03
50%    5.901630e+03
75%    1.991803e+04
max    1.467391e+07
======= Nulos ============
folioviv    0
foliohog    0
numren      0
clave       0
ing_tri     0
entidad     0
dtype: int64

     folioviv foliohog numren clave   ing_tri entidad
0  0100001901        1     01  P001  48952.17      01
1  0100001901        1     01  P004  17608.69      01
2  0100001901        1     01  P006   4402.17      01
3  0100001901        1     01  P008   4402.17      01
4  0100001901        1     01  P009   3423.91      01
5  0100001901        1     02  P001  29347.82      01
6  0100001901        1     02  P004    586.95      01
7  0100001901        1     02  P009   1222.82      01
8  0100001902        1     01  P001  46956.52      01
9  0100001902        1     01  P008   7826.08      01

## Unificar bases

In [93]:
#Crear identificador
poblacion['id_per'] = poblacion['folioviv'] + poblacion['foliohog'] + poblacion['numren'] 
ingreso['id_per']= ingreso['folioviv'] + ingreso['foliohog'] + ingreso['numren']
trabajos['id_per'] = trabajos['folioviv'] + trabajos['foliohog'] + trabajos['numren']

print(poblacion['id_per'].head(3))
print(ingreso['id_per'].head(3))
print(trabajos['id_per'].head(3))

0    0100001901101
1    0100001901102
2    0100001901103
Name: id_per, dtype: str
0    0100001901101
1    0100001901101
2    0100001901101
Name: id_per, dtype: str
0    0100001901101
1    0100001901102
2    0100001902101
Name: id_per, dtype: str

In [94]:
# Verificar si 'id_per' es único en cada tabla
print("¿Único en personas?:", poblacion["id_per"].is_unique)
print("¿Único en ingresos?:", ingreso["id_per"].is_unique)
print("¿Único en trabajos?:", trabajos["id_per"].is_unique)

¿Único en personas?: True
¿Único en ingresos?: False
¿Único en trabajos?: False

#### Nota sobre ingresos y trabajos

Se pueden dar los casos en los que una persona pueda tener mas de un ingreso y mas de un trabajo.

Por lo que se buscara la forma de cuantificar cuantos trabajos y cuantos ingresos tiene, para agrtegarlos como variable independiente, ademas de que se buscara sumarlos para que en la base final solo se tenga una entrada por persona