# Limpieza y merge de tablas de datos de enigh

In [1]:
# Importar librerias
import pandas as pd
import numpy as np

## Importacion de datos

In [2]:
# establecer columnas de datos
pob_cols = ['folioviv','foliohog','numren','sexo','edad','disc_ver','disc_oir','disc_brazo','disc_camin','disc_apren','disc_vest','disc_habla','disc_acti','nivelaprob']

ing_cols = ['folioviv','foliohog','numren','clave', 'ing_tri', 'entidad']

trab_cols = ['folioviv','foliohog', 'numren','id_trabajo','trapais','htrab', 'sinco', 'clas_emp', 'tipoact']

In [3]:
# establecer tipos de datos
tipo_pob = {
    'folioviv' : str,'foliohog' : str,'numren' : str ,'sexo' : str,'edad' : float,'disc_ver': str,'disc_oir' : str,'disc_brazo': str,'disc_camin':str,'disc_apren': str,'disc_vest':str,'disc_habla':str,'disc_acti':str,'nivelaprob':str
    }
tipo_ing = {
    'folioviv':str,'foliohog':str,'numren':str,'clave':str, 'ing_tri':float, 'entidad':str
}    
tipo_trab = {
    'folioviv':str,'foliohog':str, 'numren':str,'htrab':int, 'clas_emp': str, 'tipoact':str
}

In [152]:
# Importar datos
poblacion = pd.read_csv(r'/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Raw data/conjunto_de_datos_enigh2024_ns_csv/conjunto_de_datos_poblacion_enigh2024_ns/conjunto_de_datos/conjunto_de_datos_poblacion_enigh2024_ns.csv', usecols=pob_cols,dtype = tipo_pob)
ingreso = pd.read_csv(r'/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Raw data/conjunto_de_datos_enigh2024_ns_csv/conjunto_de_datos_ingresos_enigh2024_ns/conjunto_de_datos/conjunto_de_datos_ingresos_enigh2024_ns.csv', usecols = ing_cols, dtype = tipo_ing)
trabajos = pd.read_csv(r'/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Raw data/conjunto_de_datos_enigh2024_ns_csv/conjunto_de_datos_trabajos_enigh2024_ns/conjunto_de_datos/conjunto_de_datos_trabajos_enigh2024_ns.csv', usecols = trab_cols,dtype = tipo_trab)

In [153]:
# Tamaño
print('=== Tamaño poblacion ===')
print(poblacion.shape)
print('=== Tamaño ingreso ===')
print(ingreso.shape)
print('=== Tamaño trabajos ===')
print(trabajos.shape)

=== Tamaño poblacion ===
(308598, 14)
=== Tamaño ingreso ===
(391563, 6)
=== Tamaño trabajos ===
(164325, 9)

In [154]:
# Exploracion de poblacion
print("*************** Poblacion ********************")
print("======= descripcion cuantis =======")
print(poblacion.describe())
print("======= Nulos ============")
print(poblacion.isnull().sum())

poblacion.head(10)

*************** Poblacion ********************
======= descripcion cuantis =======
                edad
count  308598.000000
mean       33.881305
std        21.779162
min         0.000000
25%        15.000000
50%        32.000000
75%        50.000000
max       106.000000
======= Nulos ============
folioviv          0
foliohog          0
numren            0
sexo              0
edad              0
disc_ver          0
disc_oir          0
disc_brazo        0
disc_camin        0
disc_apren        0
disc_vest         0
disc_habla        0
disc_acti         0
nivelaprob    10645
dtype: int64

,folioviv,foliohog,numren,sexo,edad,disc_ver,disc_oir,disc_brazo,disc_camin,disc_apren,disc_vest,disc_habla,disc_acti,nivelaprob
0,0100001901,1,01,1,32.0,1,1,1,1,1,1,1,1,03
1,0100001901,1,02,2,24.0,1,1,1,1,1,1,1,1,04
2,0100001901,1,03,2,5.0,1,1,1,1,1,1,1,1,01
3,0100001901,1,04,1,2.0,1,1,1,1,1,1,1,1,NaN
4,0100001902,1,01,1,48.0,1,1,1,1,1,1,1,1,07
5,0100001902,1,02,2,48.0,2,1,1,1,1,1,1,1,03
6,0100001902,1,03,1,22.0,1,1,1,1,1,1,1,1,07
7,0100001902,1,04,2,16.0,1,1,1,1,1,1,1,1,04
8,0100001904,1,01,2,60.0,1,1,2,1,2,1,1,1,03
9,0100001904,1,02,1,27.0,1,1,1,1,1,1,1,1,04

In [155]:
# Exploracion de trabajos
print("*************** trabajos ********************")
print("======= descripcion cuantis =======")
print(trabajos.describe())
print("======= Nulos ============")
print(trabajos.isnull().sum())

trabajos.head(10)

*************** trabajos ********************
======= descripcion cuantis =======
          id_trabajo        trapais          htrab          sinco
count  164325.000000  164325.000000  164325.000000  164325.000000
mean        1.084850       1.003152      40.436550    6198.060691
std         0.278659       0.056057      18.702396    2650.938074
min         1.000000       1.000000       1.000000     980.000000
25%         1.000000       1.000000      28.000000    4111.000000
50%         1.000000       1.000000      43.000000    6121.000000
75%         1.000000       1.000000      48.000000    9111.000000
max         2.000000       2.000000     168.000000    9999.000000
======= Nulos ============
folioviv           0
foliohog           0
numren             0
id_trabajo         0
trapais            0
htrab              0
sinco              0
clas_emp       52114
tipoact       123157
dtype: int64

,folioviv,foliohog,numren,id_trabajo,trapais,htrab,sinco,clas_emp,tipoact
0,0100001901,1,01,1,1,48,8352,2,NaN
1,0100001901,1,02,1,1,45,5211,1,NaN
2,0100001902,1,01,1,1,48,9233,2,NaN
3,0100001902,1,03,1,1,48,9232,2,NaN
4,0100001904,1,01,1,1,12,4211,1,NaN
5,0100001904,1,01,2,1,18,4211,1,NaN
6,0100001904,1,02,1,1,40,2645,1,NaN
7,0100001905,1,01,1,1,48,8101,2,NaN
8,0100001905,1,02,1,1,10,9234,1,NaN
9,0100001905,1,03,1,1,32,9411,1,NaN

In [156]:
# Exploracion de ingreso
print("*************** ingreso ********************")
print("======= descripcion cuantis =======")
print(ingreso.describe())
print("======= Nulos ============")
print(ingreso.isnull().sum())

ingreso.head(10)

*************** ingreso ********************
======= descripcion cuantis =======
            ing_tri
count  3.915630e+05
mean   1.464697e+04
std    3.927904e+04
min    4.800000e-01
25%    1.760860e+03
50%    5.901630e+03
75%    1.991803e+04
max    1.467391e+07
======= Nulos ============
folioviv    0
foliohog    0
numren      0
clave       0
ing_tri     0
entidad     0
dtype: int64

     folioviv foliohog numren clave   ing_tri entidad
0  0100001901        1     01  P001  48952.17      01
1  0100001901        1     01  P004  17608.69      01
2  0100001901        1     01  P006   4402.17      01
3  0100001901        1     01  P008   4402.17      01
4  0100001901        1     01  P009   3423.91      01
5  0100001901        1     02  P001  29347.82      01
6  0100001901        1     02  P004    586.95      01
7  0100001901        1     02  P009   1222.82      01
8  0100001902        1     01  P001  46956.52      01
9  0100001902        1     01  P008   7826.08      01

## Unificar bases

In [157]:
#Crear identificador
poblacion['id_per'] = poblacion['folioviv'] + poblacion['foliohog'] + poblacion['numren'] 
ingreso['id_per']= ingreso['folioviv'] + ingreso['foliohog'] + ingreso['numren']
trabajos['id_per'] = trabajos['folioviv'] + trabajos['foliohog'] + trabajos['numren']


print('======== Poblacion ==========')
print(poblacion.head(3))
print('============== ingresos ==========')
print(ingreso.head(3))
print('============ Trabajos ===========')
print(trabajos.head(3))

======== Poblacion ==========
     folioviv foliohog numren sexo  edad disc_ver disc_oir disc_brazo  \
0  0100001901        1     01    1  32.0        1        1          1
1  0100001901        1     02    2  24.0        1        1          1
2  0100001901        1     03    2   5.0        1        1          1

  disc_camin disc_apren disc_vest disc_habla disc_acti nivelaprob  \
0          1          1         1          1         1         03
1          1          1         1          1         1         04
2          1          1         1          1         1         01

          id_per
0  0100001901101
1  0100001901102
2  0100001901103
============== ingresos ==========
     folioviv foliohog numren clave   ing_tri entidad         id_per
0  0100001901        1     01  P001  48952.17      01  0100001901101
1  0100001901        1     01  P004  17608.69      01  0100001901101
2  0100001901        1     01  P006   4402.17      01  0100001901101
============ Trabajos ===========
     folioviv foliohog numren  id_trabajo  trapais  htrab  sinco clas_emp  \
0  0100001901        1     01           1        1     48   8352        2
1  0100001901        1     02           1        1     45   5211        1
2  0100001902        1     01           1        1     48   9233        2

  tipoact         id_per
0     NaN  0100001901101
1     NaN  0100001901102
2     NaN  0100001902101

In [158]:
# Verificar si 'id_per' es único en cada tabla
print("¿Único en personas?:", poblacion["id_per"].is_unique)
print("¿Único en ingresos?:", ingreso["id_per"].is_unique)
print("¿Único en trabajos?:", trabajos["id_per"].is_unique)

¿Único en personas?: True
¿Único en ingresos?: False
¿Único en trabajos?: False

#### Nota sobre ingresos y trabajos

Se pueden dar los casos en los que una persona pueda tener mas de un ingreso y mas de un trabajo.

(relacion de uno a muchos)

Por lo que se buscara la forma de cuantificar cuantos trabajos y cuantos ingresos tiene, para agrtegarlos como variable independiente, ademas de que se buscara sumarlos para que en la base final solo se tenga una entrada por persona

In [159]:
# 1. Agrupar y agregar la tabla de ingresos
ingreso_agrupado = ingreso.groupby('id_per').agg(
    ing_tri_total=('ing_tri', 'sum'),      # Suma de todos los ingresos
    num_ingresos=('clave', 'count')        # Conteo de fuentes de ingreso
).reset_index()

# 2. Agrupar y agregar la tabla de trabajos
trabajos_agrupado = trabajos.groupby('id_per').agg(
    htrab_total=('htrab', 'sum'),          # Suma de horas trabajadas totales
    num_trabajos=('id_trabajo', 'count')   # Conteo de trabajos
).reset_index()

# 3. Unir las bases (Merge left para conservar a toda la poblacion)
df_final = poblacion.merge(ingreso_agrupado, on='id_per', how='left')
df_final = df_final.merge(trabajos_agrupado, on='id_per', how='left')

# 4. Rellenar nulos con 0 para personas sin trabajo/ingreso
cols_a_rellenar = ['ing_tri_total', 'num_ingresos', 'htrab_total', 'num_trabajos']
df_final[cols_a_rellenar] = df_final[cols_a_rellenar].fillna(0)

# Verificar unicidad y tamaño
print("=== Tamaño base unificada ===")
print(df_final.shape)
print("¿Único en base unificada?:", df_final['id_per'].is_unique)
df_final.head()

=== Tamaño base unificada ===
(308598, 19)
¿Único en base unificada?: True

,folioviv,foliohog,numren,sexo,edad,disc_ver,disc_oir,disc_brazo,disc_camin,disc_apren,disc_vest,disc_habla,disc_acti,nivelaprob,id_per,ing_tri_total,num_ingresos,htrab_total,num_trabajos
0,0100001901,1,01,1,32.0,1,1,1,1,1,1,1,1,03,0100001901101,78789.11,5.0,48.0,1.0
1,0100001901,1,02,2,24.0,1,1,1,1,1,1,1,1,04,0100001901102,31157.59,3.0,45.0,1.0
2,0100001901,1,03,2,5.0,1,1,1,1,1,1,1,1,01,0100001901103,0.00,0.0,0.0,0.0
3,0100001901,1,04,1,2.0,1,1,1,1,1,1,1,1,NaN,0100001901104,0.00,0.0,0.0,0.0
4,0100001902,1,01,1,48.0,1,1,1,1,1,1,1,1,07,0100001902101,56739.12,3.0,48.0,1.0

In [160]:
# Convertir discapacidad en valores 0 y 1 (False True)
cols_disc = ['disc_ver', 'disc_oir', 'disc_brazo', 'disc_camin', 
             'disc_apren', 'disc_vest', 'disc_habla', 'disc_acti']
for col in cols_disc:
    df_final[col] = df_final[col].apply(lambda x: 0 if str(x).strip() == '1' else 1)

df_final.head()

,folioviv,foliohog,numren,sexo,edad,disc_ver,disc_oir,disc_brazo,disc_camin,disc_apren,disc_vest,disc_habla,disc_acti,nivelaprob,id_per,ing_tri_total,num_ingresos,htrab_total,num_trabajos
0,0100001901,1,01,1,32.0,0,0,0,0,0,0,0,0,03,0100001901101,78789.11,5.0,48.0,1.0
1,0100001901,1,02,2,24.0,0,0,0,0,0,0,0,0,04,0100001901102,31157.59,3.0,45.0,1.0
2,0100001901,1,03,2,5.0,0,0,0,0,0,0,0,0,01,0100001901103,0.00,0.0,0.0,0.0
3,0100001901,1,04,1,2.0,0,0,0,0,0,0,0,0,NaN,0100001901104,0.00,0.0,0.0,0.0
4,0100001902,1,01,1,48.0,0,0,0,0,0,0,0,0,07,0100001902101,56739.12,3.0,48.0,1.0

In [161]:
# Variables dummie para sexo

df_final['sexo'] = df_final['sexo'].replace({'1': 'H', '2': 'F'})

# Generar las variables dummy
df_final = pd.get_dummies(df_final, columns=['sexo'], drop_first=True, dtype=int)

df_final

,folioviv,foliohog,numren,edad,disc_ver,disc_oir,disc_brazo,disc_camin,disc_apren,disc_vest,disc_habla,disc_acti,nivelaprob,id_per,ing_tri_total,num_ingresos,htrab_total,num_trabajos,sexo_H
0,0100001901,1,01,32.0,0,0,0,0,0,0,0,0,03,0100001901101,78789.11,5.0,48.0,1.0,1
1,0100001901,1,02,24.0,0,0,0,0,0,0,0,0,04,0100001901102,31157.59,3.0,45.0,1.0,0
2,0100001901,1,03,5.0,0,0,0,0,0,0,0,0,01,0100001901103,0.00,0.0,0.0,0.0,0
3,0100001901,1,04,2.0,0,0,0,0,0,0,0,0,NaN,0100001901104,0.00,0.0,0.0,0.0,1
4,0100001902,1,01,48.0,0,0,0,0,0,0,0,0,07,0100001902101,56739.12,3.0,48.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308593,3260593816,1,05,12.0,0,0,0,0,0,0,0,0,02,3260593816105,0.00,0.0,0.0,0.0,1
308594,3260593817,1,01,53.0,0,0,0,0,1,0,0,0,02,3260593817101,0.00,0.0,0.0,0.0,1
308595,3260593817,1,02,54.0,0,0,0,0,0,1,0,0,02,3260593817102,3344.26,1.0,168.0,1.0,0
308596,3260593818,1,01,63.0,0,0,0,0,0,0,0,0,03,3260593818101,7131.14,1.0,24.0,1.0,0
308597,3260593818,1,02,40.0,0,0,0,0,0,0,0,0,02,3260593818102,15393.43,2.0,40.0,1.0,1

In [162]:
# Eliminar personas menores de 12 años
df_final = df_final[df_final['edad'] >= 12].copy()

# Verificar el cambio en el número de filas
print("=== Tamaño final ===")
print(df_final.shape)

df_final.head()

=== Tamaño final ===
(252527, 19)

,folioviv,foliohog,numren,edad,disc_ver,disc_oir,disc_brazo,disc_camin,disc_apren,disc_vest,disc_habla,disc_acti,nivelaprob,id_per,ing_tri_total,num_ingresos,htrab_total,num_trabajos,sexo_H
0,0100001901,1,01,32.0,0,0,0,0,0,0,0,0,03,0100001901101,78789.11,5.0,48.0,1.0,1
1,0100001901,1,02,24.0,0,0,0,0,0,0,0,0,04,0100001901102,31157.59,3.0,45.0,1.0,0
4,0100001902,1,01,48.0,0,0,0,0,0,0,0,0,07,0100001902101,56739.12,3.0,48.0,1.0,1
5,0100001902,1,02,48.0,1,0,0,0,0,0,0,0,03,0100001902102,0.00,0.0,0.0,0.0,0
6,0100001902,1,03,22.0,0,0,0,0,0,0,0,0,07,0100001902103,29347.82,1.0,48.0,1.0,1

In [164]:
# Guardar dataframe final
df_final.to_csv('/run/media/oswal/01DD260F5154F4B0/Duend/Documentos/1 IA y ciencia de datos/Semestre 3/proyecto integrador/Clean data/clean_data.csv', index=False, encoding='utf-8')